### ISSUE TITLE
Fails to build with GCC 7.1.0

### ISSUE THREAD

**Issue by JDonner** [triSYCL/triSYCL#57]
It's pretty simple, it's failing to recognize {} as a general initialization form instead of as an initializer list. It might be a GCC bug, as clang 4.0.1 handles it fine. 
I'm using Ubuntu 16.04, with hand-installed GCC and Clang. 
```
.../triSYCL/build> g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/gcc-7.1/libexec/gcc/x86_64-pc-linux-gnu/7.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-7.1.0/configure --prefix=/usr/local/gcc-7.1 --with-gmp=/usr/local/gmp --with-mpfr=/usr/local/mpfr --disable-multilib
Thread model: posix
gcc version 7.1.0 (GCC) 
```

error:

```
.../triSYCL/build> make
cd /space/software/triSYCL/build/tests/buffer && /usr/local/gcc/bin/g++   -I/space/software/triSYCL/include -I/space/software/triSYCL/tests/common -I/usr/include/compute  -Wall -Wextra -Wno-ignored-attributes -Wno-sign-compare -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-parameter -fopenmp -std=gnu++1z -o CMakeFiles/buffer_buffer_unique_ptr.dir/buffer_unique_ptr.cpp.o -c /space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp
/space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp: In function ‘int test_main(int, char**)’:
/space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp:20:38: error: no matching function for call to ‘cl::sycl::buffer<int>::buffer(<brace-enclosed initializer list>)’
   buffer<int> a { std::move(init), N };
                                      ^
In file included from /space/software/triSYCL/include/CL/sycl.hpp:40:0,
                 from /space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp:8:
/space/software/triSYCL/include/CL/sycl/buffer.hpp:321:3: note: candidate: cl::sycl::buffer<T, Dimensions, Allocator>::buffer(cl::sycl::buffer<T, Dimensions, Allocator>&, const cl::sycl::id<Dimensions>&, const cl::sycl::range<Dimensions>&, Allocator) [with T = int; int Dimensions = 1; Allocator = std::allocator<int>]
   buffer(buffer<T, Dimensions, Allocator> &b,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:321:3: note:   candidate expects 4 arguments, 2 provided
/space/software/triSYCL/include/CL/sycl/buffer.hpp:299:3: note: candidate: template<class InputIterator, class ValueType> cl::sycl::buffer<T, Dimensions, Allocator>::buffer(InputIterator, InputIterator, Allocator)
   buffer(InputIterator start_iterator,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:299:3: note:   template argument deduction/substitution failed:
/space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp:20:38: note:   deduced conflicting types for parameter ‘InputIterator’ (‘std::unique_ptr<int []>’ and ‘long unsigned int’)
   buffer<int> a { std::move(init), N };
                                      ^
In file included from /space/software/triSYCL/include/CL/sycl.hpp:40:0,
                 from /space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp:8:
/space/software/triSYCL/include/CL/sycl/buffer.hpp:254:3: note: candidate: cl::sycl::buffer<T, Dimensions, Allocator>::buffer(cl::sycl::unique_ptr_class<T>&&, const cl::sycl::range<Dimensions>&, Allocator) [with T = int; int Dimensions = 1; Allocator = std::allocator<int>; cl::sycl::unique_ptr_class<T> = std::unique_ptr<int [], std::default_delete<int> >]
   buffer(unique_ptr_class<T> &&host_data,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:254:3: note:   no known conversion for argument 1 from ‘std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}’ to ‘cl::sycl::unique_ptr_class<int, std::default_delete<int> >&& {aka std::unique_ptr<int [], std::default_delete<int> >&&}’
/space/software/triSYCL/include/CL/sycl/buffer.hpp:227:3: note: candidate: cl::sycl::buffer<T, Dimensions, Allocator>::buffer(cl::sycl::shared_ptr_class<T>, const cl::sycl::range<Dimensions>&, Allocator) [with T = int; int Dimensions = 1; Allocator = std::allocator<int>; cl::sycl::shared_ptr_class<T> = std::shared_ptr<int>]
   buffer(shared_ptr_class<T> host_data,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:227:3: note:   no known conversion for argument 1 from ‘std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}’ to ‘cl::sycl::shared_ptr_class<int> {aka std::shared_ptr<int>}’
/space/software/triSYCL/include/CL/sycl/buffer.hpp:199:3: note: candidate: cl::sycl::buffer<T, Dimensions, Allocator>::buffer(cl::sycl::shared_ptr_class<T>&, const cl::sycl::range<Dimensions>&, cl::sycl::mutex_class&, Allocator) [with T = int; int Dimensions = 1; Allocator = std::allocator<int>; cl::sycl::shared_ptr_class<T> = std::shared_ptr<int>; cl::sycl::mutex_class = std::mutex]
   buffer(shared_ptr_class<T> &host_data,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:199:3: note:   candidate expects 4 arguments, 2 provided
/space/software/triSYCL/include/CL/sycl/buffer.hpp:170:3: note: candidate: cl::sycl::buffer<T, Dimensions, Allocator>::buffer(T*, const cl::sycl::range<Dimensions>&, Allocator) [with T = int; int Dimensions = 1; Allocator = std::allocator<int>]
   buffer(T *host_data,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:170:3: note:   no known conversion for argument 1 from ‘std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}’ to ‘int*’
/space/software/triSYCL/include/CL/sycl/buffer.hpp:146:3: note: candidate: template<class Dependent, class> cl::sycl::buffer<T, Dimensions, Allocator>::buffer(const T*, const cl::sycl::range<Dimensions>&, Allocator)
   buffer(const T *host_data,
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:146:3: note:   template argument deduction/substitution failed:
/space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp:20:28: note:   cannot convert ‘std::move<std::unique_ptr<int []>&>(init)’ (type ‘std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}’) to type ‘const int*’
   buffer<int> a { std::move(init), N };
                   ~~~~~~~~~^~~~~~
In file included from /space/software/triSYCL/include/CL/sycl.hpp:40:0,
                 from /space/software/triSYCL/tests/buffer/buffer_unique_ptr.cpp:8:
/space/software/triSYCL/include/CL/sycl/buffer.hpp:113:3: note: candidate: cl::sycl::buffer<T, Dimensions, Allocator>::buffer(const cl::sycl::range<Dimensions>&, Allocator) [with T = int; int Dimensions = 1; Allocator = std::allocator<int>]
   buffer(const range<Dimensions> &r, Allocator allocator = {})
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:113:3: note:   no known conversion for argument 1 from ‘std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}’ to ‘const cl::sycl::range<1>&’
/space/software/triSYCL/include/CL/sycl/buffer.hpp:98:3: note: candidate: constexpr cl::sycl::buffer<T, Dimensions, Allocator>::buffer() [with T = int; int Dimensions = 1; Allocator = std::allocator<int>]
   buffer() = default;
   ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:98:3: note:   candidate expects 0 arguments, 2 provided
/space/software/triSYCL/include/CL/sycl/buffer.hpp:62:7: note: candidate: cl::sycl::buffer<int>::buffer(const cl::sycl::buffer<int>&)
 class buffer
       ^~~~~~
/space/software/triSYCL/include/CL/sycl/buffer.hpp:62:7: note:   candidate expects 1 argument, 2 provided
/space/software/triSYCL/include/CL/sycl/buffer.hpp:62:7: note: candidate: cl::sycl::buffer<int>::buffer(cl::sycl::buffer<int>&&)
/space/software/triSYCL/include/CL/sycl/buffer.hpp:62:7: note:   candidate expects 1 argument, 2 provided
tests/buffer/CMakeFiles/buffer_buffer_unique_ptr.dir/build.make:65: recipe for target 'tests/buffer/CMakeFiles/buffer_buffer_unique_ptr.dir/buffer_unique_ptr.cpp.o' failed
```

**Comment by keryell** [comment]
That is strange because I thought this was fixed by https://github.com/triSYCL/triSYCL/pull/55

Is this different from https://github.com/triSYCL/triSYCL/issues/48 ?

**Comment by JDonner** [comment]
I don't know, but I've gotten it to build with clean with GCC 7.1.0 and 7.2.0, now. I can only think my earlier build was messed up something, and perhaps buffer clashing with something else.

**Comment by keryell** [comment]
Nice. I love that.
