### ISSUE TITLE
Device compiler unusable?

### ISSUE THREAD

**Issue by j-stephan** [triSYCL/triSYCL#240]
I've tried to use the triSYCL versions of LLVM and clang. Following the build instructions given in the architecture README, I managed to compile both the `master` and the `release_70` branches. However, upon compiling the test cases I end up with the following error on both Ubuntu 18.04 and Ubuntu 16.04 and the Boost versions 1.68 and 1.65:

```
$ make device_compiler/single_task_vector_add_drt.kernel_caller
/home/jstephan/software/triSYCL/llvm-device/bin/clang++  -DTRISYCL_OPENCL -g -Wall -Wno-ignored-attributes -std=c++1z -I/home/jstephan/triSYCL/triSYCL/include -I/home/jstephan/triSYCL/triSYCL/tests/common -DBOOST_COMPUTE_DEBUG_KERNEL_COMPILATION -DBOOST_COMPUTE_HAVE_THREAD_LOCAL -DBOOST_COMPUTE_THREAD_SAFE -sycl -DTRISYCL_USE_OPENCL_ND_RANGE \
  -emit-llvm -S -o device_compiler/single_task_vector_add_drt.pre_kernel_caller.ll device_compiler/single_task_vector_add_drt.cpp
In file included from device_compiler/single_task_vector_add_drt.cpp:6:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl.hpp:31:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/detail/global_config.hpp:51:
In file included from /opt/spack-modules/linux-ubuntu16.04-x86_64/gcc-5.4.0/boost-1.68.0-5o6jqkacrhkhpmvqhw3hjzi7ps3nczzx/include/boost/compute.hpp:14:
In file included from /opt/spack-modules/linux-ubuntu16.04-x86_64/gcc-5.4.0/boost-1.68.0-5o6jqkacrhkhpmvqhw3hjzi7ps3nczzx/include/boost/compute/algorithm.hpp:18:
In file included from /opt/spack-modules/linux-ubuntu16.04-x86_64/gcc-5.4.0/boost-1.68.0-5o6jqkacrhkhpmvqhw3hjzi7ps3nczzx/include/boost/compute/algorithm/accumulate.hpp:17:
In file included from /opt/spack-modules/linux-ubuntu16.04-x86_64/gcc-5.4.0/boost-1.68.0-5o6jqkacrhkhpmvqhw3hjzi7ps3nczzx/include/boost/compute/system.hpp:14:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/string:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/basic_string.h:5249:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/string_conversions.h:43:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/cstdio:42:
In file included from /usr/include/stdio.h:74:
/usr/include/libio.h:376:67: error: access qualifier can only be used for pipe and image type
extern void _IO_cookie_init (struct _IO_cookie_file *__cfile, int __read_write,
                                                                  ^
```

On Ubuntu 16.04 this is followed by the following error:

```
In file included from device_compiler/single_task_vector_add_drt.cpp:6:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl.hpp:37:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/accessor.hpp:15:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/accessor/detail/local_accessor.hpp:21:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/command_group/detail/task.hpp:23:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/buffer/detail/buffer_base.hpp:27:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/context.hpp:14:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/context/detail/host_context.hpp:18:
In file included from /home/jstephan/triSYCL/triSYCL/include/CL/sycl/context/detail/context.hpp:12:
/home/jstephan/triSYCL/triSYCL/include/CL/sycl/device.hpp:14:10: fatal error: 'any' file not found
#include <any>
         ^~~~~
```

I've also tried to use the `release_39` branch but compilation fails:

```
[ 68%] Building CXX object tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/BackendUtil.cpp.o
/home/jstephan/triSYCL/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp: In member function ‘void {anonymous}::EmitAssemblyHelper::CreatePasses(llvm::legacy::PassManager&, llvm::legacy::FunctionPassManager&, llvm::ModuleSummaryIndex*)’:
/home/jstephan/triSYCL/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:482:15: error: ‘class {anonymous}::PassManagerBuilderWrapper’ has no member named ‘EnableLoopIdiom’
     PMBuilder.EnableLoopIdiom = false;
               ^
tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/build.make:62: recipe for target 'tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/BackendUtil.cpp.o' failed
make[2]: *** [tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/BackendUtil.cpp.o] Error 1
CMakeFiles/Makefile2:8950: recipe for target 'tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/all' failed
make[1]: *** [tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

If I am missing anything I'd be grateful for some hints.

**Comment by keryell** [comment]
I am sorry about all your problems.
Interesting to see that in the GNU libstdc++ 5.4 there is a parameter name which is the same as an OpenCL C attribute... :-/

Actually we work on Ubuntu 18.10 + Clang/LLVM from the trunk, or g++ 8.2 or clang++ 7.
Ubuntu 16.04 is already 3 year old and `std::any` is from C++17... :-(

It looks like we forgot to bump the versions in the documentation about the minimal requirements :-( , specially for the device compiler version where we often use the latest version of Clang anyway because we have to compile it. If you target CPU only, you might have more chance with older compiler and this is only what is validated on Travis-CI now.

`release_39` is definitely obsolete. You should use the branch `master` from the Clang and LLVM in triSYCL repositories, which are 3 months before the recent 8.0.0.
But we should make public next week or the week after a new branch with our LLVM passes rebased on the Intel SYCL compiler to have a better user experience with a true Clang driver instead of a cryptic Makefile... So I think it is better to wait for this version.

**Comment by j-stephan** [comment]
OK, I'll try to set up Ubuntu 18.10 somewhere. Will I be able to run SDAccel 2018.3 on it? I remember that either Ubuntu 16.04 or 18.04 are a requirement.

**Comment by keryell** [comment]
SDAccel 2018.3 is not supported on Ubuntu 18.10 but we found it quite usable. Now since XRT has been open-sourced you can compile it on a recent Linux. Do not forget that SYCL is a research project for now, not a product... :-)

**Comment by keryell** [comment]
Perhaps you could try this version now https://github.com/triSYCL/sycl

**Comment by j-stephan** [comment]
Closing this now since the experimental compiler at https://github.com/triSYCL/sycl is usable.
