### ISSUE TITLE
pipe_observers.cpp fails to build on gcc 8.1

### ISSUE THREAD

**Issue by airlied** [triSYCL/triSYCL#147]
On Fedora 28:
gcc version 8.1.1 20180502 (Red Hat 8.1.1-1) (GCC)

home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp: In instantiation of ‘<lambda(auto:5&, cl::sycl::pipe<char>&)> [with auto:5 = cl::sycl::queue]’:
/home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:69:3:   required from here
/home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:48:11: error: passing ‘const cl::sycl::accessor<bool, 1, (cl::sycl::access::mode)43, (cl::sycl::access::target)2014>’ as ‘this’ argument discards qualifiers [-fpermissive]
           *v = p.METHOD();                                              \
           ^~
/home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:56:1: note: in expansion of macro ‘MAKE_GET_OBSERVER’
 MAKE_GET_OBSERVER(empty, bool);
 ^~~~~~~~~~~~~~~~~
In file included from /home/airlied/devel/compute/trisycl/include/CL/sycl.hpp:37,
                 from /home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:5:
/home/airlied/devel/compute/trisycl/include/CL/sycl/accessor.hpp:294:39: note:   in call to ‘typename cl::sycl::accessor<DataType, Dimensions, AccessMode, Target>::accessor_detail::reference cl::sycl::accessor<DataType, Dimensions, AccessMode, Target>::operator*() [with DataType = bool; int Dimensions = 1; cl::sycl::access::mode AccessMode = (cl::sycl::access::mode)43; cl::sycl::access::target Target = (cl::sycl::access::target)2014; typename cl::sycl::accessor<DataType, Dimensions, AccessMode, Target>::accessor_detail::reference = bool&]’
   typename accessor_detail::reference operator*() {
                                       ^~~~~~~~

**Comment by keryell** [comment]
You solved it with https://github.com/triSYCL/triSYCL/commit/18572c309b795fca9f5b3e72827dde4349ca7453

Thanks.
